#!/bin/bash

if [ "$1" = "--debug" ]; then
  echo "Running perl6 script in debug mode..."
  EXEC=rakudo-gdb-m
  shift
elif [ "$1" = "--valgrind" ]; then
  echo "Running perl6 script in valgrind mode..."
  EXEC=rakudo-valgrind-m
  shift
elif [ "$1" = "--rr" ]; then
  EXEC=rr
  shift
elif [ "$1" = "--pbuild" ]; then
  PARALLEL_BUILD=1
  EXEC=raku
  shift
else
  #echo "Running perl6 script..."
  EXEC=raku
fi

INCLUDES="\
-I${P6_GTK_HOME}/raku-ProtoTools/lib \
-Ilib -Ibin"

# Handle any extra directories in project file.
MOREI=`grep libdir .p6-gtk-project | \
cut -d= -f 2 | \
raku -ne '.say for .lines.split(",")'`
for a in $MOREI; do INCLUDES="-I$a $INCLUDES"; done

if [[ -z "${PARALLEL_BUILD}" ]]; then
  if [ "$EXEC" = "rr" ]; then
    rr record -M -- raku --stagestats ${EXTRAS} ${INCLUDES} "$@"
  else
    ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@"
  fi
else
  ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@" 
fi
